
FROM node:24-alpine

COPY . /opt

WORKDIR /opt

RUN npm install && npm run build

RUN rm -f /var/www/localhost/*

RUN cp -rf dist/* /var/www/localhost/

RUN apk update && apk add apache2


EXPOSE 80



CMD ["httpd", "-D", "FOREGROUND"]